//Annonce Actions
export const GET_ANNONCE="GET_ANNONCE"
export const ADD_ANNONCE="ADD_ANNONCE"
export const DELETE_ANNONCE="DELETE_ANNONCE"
export const UPDATE_ANNONCE="UPDATE_ANNONCE"
export const SAVE_ANNONCE="SAVE_ANNONCE"
export const ClEAR_ANNONCE="ClEAR_ANNONCE"
export const ANNONCE_ERROR="ANNONCE_ERROR"
export const REMOVE_CURRENT_ANNONCE=" REMOVE_CURRENT_ANNONCE"

export const GET_All_ANNONCE="GET_All_ANNONCE"


//Auth actions
export const REGISTER_SUCCES="REGISTER_SUCCES"
export const REGISTER_FAIL="REGISTER_FAIL"
export const LOGIN_SUCCES="LOGIN_SUCCES"
export const USER_LOGED="USER_LOGED"
export const LOGIN_FAIL="LOGIN_FAIL"
export const AUTH_ERRORS="AUTH_ERRORS"
export const CLEAR_ERRORS="CLEAR_ERRORS"
export const LOGOUT="LOGOUT"

//Alert actions
export const SET_ALERT="SET_ALERT"
export const REMOVE_ALERT="REMOVE_ALERT"